apiVersion: v1
kind: Service
metadata:
  name: geode-locator
  labels:
    app: geode-locator
spec:
  type: ClusterIP
  ports:
    - name: locator-traffic
      port: 10334
      targetPort: 10334
      protocol: TCP
    - name: pulse-traffic
      port: 7070
      targetPort: 7070
      protocol: TCP
  selector:
    app: geode-locator
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geode-locator
  labels:
    app: geode-locator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geode-locator
  serviceName: geode-locator
  template:
    metadata:
      labels:
        app: geode-locator
    spec:
      containers:
        - name: geode-locator
          image: "apachegeode/geode:latest"
          imagePullPolicy: IfNotPresent
          command:
          - sh
          - -c
          - |
            gfsh -e "start locator --name=${HOSTNAME} --dir=/data \
            --max-heap=128m --hostname-for-clients=$(hostname -i) \
            --bind-address=$(hostname -i) --jmx-manager-hostname-for-clients=$(hostname -i) \
            --http-service-port=7070 \
            --J=-Dgemfire.log-file=/var/log/locator.log" \
            -e "configure pdx --read-serialized=true --disk-store=DEFAULT" && \
            tail -f /var/log/locator.log
          ports:
            - name: locator
              containerPort: 10334
            - name: jmx
              containerPort: 1099
            - name: pulse
              containerPort: 7070