apiVersion: v1
kind: Service
metadata:
  name: geode-server
  labels:
    app: geode-server
spec:
  type: ClusterIP
  ports:
    - name: server
      port: 40404
      targetPort: 40404
      protocol: TCP
    - name: jmx
      port: 1099
      targetPort: 1099
      protocol: TCP
  selector:
    app: geode-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geode-server
  labels:
    app: geode-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: geode-server
  serviceName: geode-server
  template:
    metadata:
      labels:
        app: geode-server
    spec:
      containers:
        - name: geode
          image: "apachegeode/geode:latest"
          imagePullPolicy: IfNotPresent
          command:
          - sh
          - -c
          - |
            gfsh start server --name=${HOSTNAME} --dir=/data --J=-Dgemfire.locator-wait-time=100 \
            --locators=geode-locator[10334] \
            --max-heap=256m --hostname-for-clients=$(hostname -i) \
            --bind-address=$(hostname -i) --jmx-manager-hostname-for-clients=$(hostname -i) \
            --J=-Dgemfire.log-file=/var/log/server.log && \
            tail -f /var/log/server.log
          ports:
            - name: server
              containerPort: 40404
            - name: jmx
              containerPort: 1099
  volumeClaimTemplates:
    - metadata:
        name: geode-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi