apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker
  labels:
    app: kafka-broker
    component: kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
      component: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
        component: kafka-broker
    spec:
      containers:
        - name: kafka-broker
          image: wurstmeister/kafka:latest
          ports:
            - containerPort: 9092
          env:
            - name: ENABLE_AUTO_EXTEND
              value: "true"
            - name: KAFKA_RESERVED_BROKER_MAX_ID
              value: "999999999"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: kafka-zk:2181
