kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres-file-source
  labels:
    app: postgres-file-source
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres-file-source
  template:
    metadata:
      labels:
        app: postgres-file-source
    spec:
      containers:
        - name: postgres-scs-file-source
          image: springcloudstream/file-source-kafka:latest
          ports:
            - containerPort: 8080
            - containerPort: 80
              protocol: TCP
          env:
            - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
              value: kafka
            - name: SERVER_PORT
              value: '80'
            - name: SPRING_CLOUD_STREAM_BINDINGS_INPUT_GROUP
              value: postgres-processor-stream
            - name: SPRING_CLOUD_STREAM_BINDINGS_OUTPUT_DESTINATION
              value:  postgres-file-source
            - name: SPRING_CLOUD_STREAM_BINDINGS_OUTPUT_PRODUCER_PARTITION-COUNT
              value: "8"
            - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_AUTOADDPARTITIONS
              value: "true"
            - name: file.directory
              value: /tmp/foo/
            - name: file.consumer.mode
              value: lines
            - name: debug
              value: 'true'
            - name: logging.file
              value: /home/spring-boot.log
            - name: logging.file.max-size
              value: 100MB
      restartPolicy: Always
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres-processor
  labels:
    app: postgres-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres-processor
  template:
    metadata:
      labels:
        app: postgres-processor
    spec:
      containers:
        - name: postgres-processor
          image: jhenfuseio/postgres-processor
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
              value: kafka
            - name: SPRING_CLOUD_STREAM_BINDINGS_INPUT_GROUP
              value: postgres-processor-stream
            - name: SPRING_CLOUD_STREAM_BINDINGS_OUTPUT_DESTINATION
              value:  postgres-processor
            - name: SPRING_CLOUD_STREAM_BINDINGS_INPUT_DESTINATION
              value: postgres-file-source
            - name: SERVER_PORT
              value: '80'
            - name: spring.datasource.driver-class-name
              value: org.postgresql.Driver
            - name: spring.datasource.password
              value: app
            - name: spring.datasource.url
              value: jdbc:postgresql://localhost:5432/app
            - name: spring.datasource.username
              value: app
            - name: debug
              value: 'true'
            - name: logging.file
              value: /home/spring-boot.log
            - name: logging.file.max-size
              value: 100MB