spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://postgres:5432/app
    driverClassName: org.postgresql.Driver
    username: app
    password: app
management:
  endpoints:
    web:
      exposure:
        include: health,info,bindings,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
